spring:
  datasource:
    url: jdbc:postgresql://eduvibepostgresserver.postgres.database.azure.com:5432/EduVibeDatabase
    username: postgres@eduvibepostgresserver
    password: Ms12345678
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 123456
#    url: jdbc:postgresql://eduvibe-server.postgres.database.azure.com:5432/eduvibe-database
#    username: inxbtxsybp
#    password: 52eXnXBQS7a$KA$G

    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/eduvibe
          jwk-set-uri: http://localhost:8083/auth/realms/eduvibe/protocol/openid-connect/certs